# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "oauth-jwks"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "test-oauth-jwks"
s3_prefix = "test-oauth-jwks"
region = "eu-west-2"
parameter_overrides = "Environment=\"test\" KeyRotationFrequency=\"30\" TokenUrl=\"https://int.api.service.nhs.uk/oauth2/token\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
[test.deploy.parameters]
stack_name = "test-oauth-jwks"
resolve_s3 = true
s3_prefix = "test-oauth-jwks"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"test\" KeyRotationFrequency=\"30\""
image_repositories = []
